#!/bin/bash
sed -i 's/e+/D+/g' $1   # Convert QChem wfn exponent format
sed -i 's/e-/D-/g' $1   # Convert QChem wfn exponent format

sed -i 's/-/ -/g' $1
sed -i 's/D -/D-/g' $1
sed -i 's/CENTRE/CENTRE /' $1
sed -i 's/  / /g' $1


